### ISSUE TITLE
The google analytics snippet

### ISSUE THREAD

**Issue by ayebaishmo** [Richie9000/Portfolio-setup#9]
Hey buddy so far so good.
Like i said within the review. The google analytics snippet should be in between the head tag. here is the reason why:
Putting it in the head helps to ensure your metrics even when the user dose not let the page to finish loading.

**Comment by Richie9000** [comment]
Yeah, that's right, I'm going to work on that. Thanks!

**Comment by er-contreras** [comment]
@ayebaishmo has right it is better to practice to keep the script of google analytics inside the head of HTML.
